repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    # -   id: flake8
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3

# -   repo: https://github.com/pycqa/flake8
#     rev: ''
#     hooks:
#     -   id: flake8

# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v2.0.0
#     hooks:
#     - id: flake8
