"""Added table

Revision ID: 13437d6535a0
Revises: 1f589ce79177
Create Date: 2022-12-12 15:19:25.246744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13437d6535a0"
down_revision = "1f589ce79177"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entry", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entry", "is_active")
    # ### end Alembic commands ###
